// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhCnePK0JxgzmMg2Dx2gUgGEyPpfUC5l4',
    appId: '1:324875915553:web:9c8b1136a2d04594bcae60',
    messagingSenderId: '324875915553',
    projectId: 'treesure-6496c',
    authDomain: 'treesure-6496c.firebaseapp.com',
    storageBucket: 'treesure-6496c.firebasestorage.app',
    measurementId: 'G-G9V6QMHX1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD59JpWFMXMnGAld4_7X27lhp0vyzj_YSQ',
    appId: '1:324875915553:android:dac296b4fdc8218bbcae60',
    messagingSenderId: '324875915553',
    projectId: 'treesure-6496c',
    storageBucket: 'treesure-6496c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhCnePK0JxgzmMg2Dx2gUgGEyPpfUC5l4',
    appId: '1:324875915553:web:f1c248900d950faabcae60',
    messagingSenderId: '324875915553',
    projectId: 'treesure-6496c',
    authDomain: 'treesure-6496c.firebaseapp.com',
    storageBucket: 'treesure-6496c.firebasestorage.app',
    measurementId: 'G-K3JGEJT1WJ',
  );
}
